# COPYRIGHT Dassault Systemes 2009
#======================================================================
# Imakefile for module JLJptypes.m
#======================================================================
#
#  Mar 2009  Creation: Code generated by the CAA wizard  u62xz
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES)

# System dependant variables
#
OS = AIX
LOCAL_POST_CCFLAGS = -D__JLJptypes -DNDEBUG -O3 \
-qarch=auto -qwarn64 -qthreaded -qinline -qstaticinline -qnotemplateregistry -qeh=v6 -qrtti 
LOCAL_LDFLAGS = -qipa -lpthreads
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
LOCAL_POST_CCFLAGS = -DNDEBUG -D__JLJptypes -GR -EHsc
LOCAL_LDFLAGS = 
SYS_LIBS = ws2_32.lib rpcrt4.lib
