# COPYRIGHT Dassault Systemes 2009
#======================================================================
# Imakefile for module JMSTOOLSutil.m
#======================================================================
#
#  Nov 2007  Creation: Code generated by the CAA wizard  b5631
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = \
JS0GROUP \
zlib1 \
xerces-c \
xqilla \
cppunit \
JLJptypes \
JLJcore \
JLJlang \
JLJio \
JLJnio \
JLJnet \
JLJutil \
JLJxml \
JLJjms \
JLJnaming \
JLJlifetime 
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES)

# System dependant variables
#
OS = AIX
LOCAL_POST_CCFLAGS = \
-DNDEBUG -DU1 -D__JMSTOOLSutil -O3 -qarch=auto -qthreaded -qinline -qstaticinline \
-qnotemplateregistry -qeh=v6 -qrtti
LOCAL_LDFLAGS = -qipa -lpthreads -bhalt:8 -qsuppress=1586-233:1586-231
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
LOCAL_POST_CCFLAGS = \
-DNDEBUG -DU2 -D__JMSTOOLSutil -GR -EHsc 
LOCAL_LDFLAGS =

